import type { Metadata } from "next";
import { Mulish , Atkinson_Hyperlegible } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
})

const atkinsonHyperlegible = Atkinson_Hyperlegible({
  variable: "--font-atkinson-hyperlegible",
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${atkinsonHyperlegible.className} antialiased`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
